sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t frontier-sco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true frontier-sco/react-test npm test

after_success:
  - docker build -t frontier-sco/multi-client ./client
  - docker build -t frontier-sco/multi-nginx ./nginx
  - docker build -t frontier-sco/multi-server ./server
  - docker build -t frontier-sco/multi-worker ./worker


# Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# take these images and push them to docker hub
  - docker push frontiersco/multi-client
  - docker push frontiersco/multi-nginx
  - docker push frontiersco/multi-server
  - docker push frontiersco/multi-worker

