sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t frontier-sco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true frontier-sco/react-test npm test

after_success:
  - docker build -t frontiersco/multi-client ./client
  - docker build -t frontiersco/multi-nginx ./nginx
  - docker build -t frontiersco/multi-server ./server
  - docker build -t frontiersco/multi-worker ./worker

# Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# take these images and push them to docker hub
  - docker push frontiersco/multi-client
  - docker push frontiersco/multi-nginx
  - docker push frontiersco/multi-server
  - docker push frontiersco/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-054306867602'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
